export const de = {
  common: {
    loading: 'Wird geladen...',
    error: 'Fehler',
    retry: 'Wiederholen',
    settings: 'Einstellungen',
    cancel: 'Abbrechen',
    save: 'Speichern',
    delete: 'Löschen',
    edit: 'Bearbeiten',
    search: 'Suchen',
    ok: 'OK',
  },
  settings: {
    title: 'Einstellungen',
    appearance: 'Erscheinungsbild',
    theme: 'Thema',
    language: 'Sprache',
    dark: 'Dunkel',
    light: 'Hell',
    system: 'System',
    english: 'Englisch',
    russian: 'Russisch',
    spanish: 'Spanisch',
    german: 'Deutsch',
    about: 'Über',
    version: 'Version',
    units: 'Einheiten',
    metric: 'Metrisch',
    imperial: 'Imperial',
  },
  weather: {
    temperature: 'Temperatur',
    humidity: 'Luftfeuchtigkeit',
    wind: 'Wind',
    pressure: 'Luftdruck',
    feelsLike: 'Gefühlt wie',
    sunrise: 'Sonnenaufgang',
    sunset: 'Sonnenuntergang',
    clear: 'Klar',
    cloudy: 'Bewölkt',
    rain: 'Regen',
    snow: 'Schnee',
    visibility: 'Sichtweite',
    precipitation: 'Niederschlag',
    forecast: 'Vorhersage',
    uvIndex: 'UV-Index',
    uvLow: 'Niedrig',
    uvModerate: 'Mäßig',
    uvHigh: 'Hoch',
    uvVeryHigh: 'Sehr hoch',
    uvExtreme: 'Extrem',
    hourlyForecast: 'Stündliche Vorhersage',
    dailyForecast: '7-Tage-Vorhersage',
    temperatureChart: 'Temperaturdiagramm',
    overcast: 'Bewölkt',
  },
  locations: {
    currentLocation: 'Aktueller Standort',
    searchPlaceholder: 'Stadt suchen...',
    favorites: 'Lieblingsstädte',
    addToFavorites: 'Zu Favoriten hinzufügen',
    removeFromFavorites: 'Aus Favoriten entfernen',
    detectLocation: 'Standort erkennen',
    current: 'Aktueller Standort',
  },
  astronomical: {
    title: 'Astronomische Daten',
    sunrise: 'Sonnenaufgang',
    sunset: 'Sonnenuntergang',
    moonrise: 'Mondaufgang',
    moonset: 'Monduntergang',
    illumination: 'Mondbeleuchtung',
    newmoon: 'Neumond',
    waxingcrescent: 'Zunehmender Sichelmond',
    firstquarter: 'Erstes Viertel',
    waxinggibbous: 'Zunehmender Mond',
    fullmoon: 'Vollmond',
    waninggibbous: 'Abnehmender Mond',
    lastquarter: 'Letztes Viertel',
    waningcrescent: 'Abnehmender Sichelmond',
  },
  airQuality: {
    title: 'Luftqualität',
    good: 'Gut',
    moderate: 'Mäßig',
    unhealthyForSensitive: 'Ungesund für empfindliche Gruppen',
    unhealthy: 'Ungesund',
    veryUnhealthy: 'Sehr ungesund',
    hazardous: 'Gefährlich',
    unknown: 'Unbekannt',
    index: 'EPA-Index',
  },
  units: {
    temperature: '°C',
    speed: 'km/h',
    pressure: 'hPa',
    precipitation: 'mm',
    distance: 'km',
  },
  unitsImperial: {
    temperature: '°F',
    speed: 'mph',
    pressure: 'inHg',
    precipitation: 'in',
    distance: 'mi',
  },
  directions: {
    N: 'N',
    NNE: 'NNO',
    NE: 'NO',
    ENE: 'ONO',
    E: 'O',
    ESE: 'OSO',
    SE: 'SO',
    SSE: 'SSO',
    S: 'S',
    SSW: 'SSW',
    SW: 'SW',
    WSW: 'WSW',
    W: 'W',
    WNW: 'WNW',
    NW: 'NW',
    NNW: 'NNW',
  },
  recommendations: {
    title: 'Empfehlungen',
    clothing: {
      warm: 'Tragen Sie warme Kleidung',
      light: 'Leichte Kleidung reicht aus',
      raincoat: 'Nehmen Sie einen Regenschirm oder Regenmantel mit',
      winter: 'Tragen Sie warme Winterkleidung',
    },
    activities: {
      perfect: 'Perfektes Wetter für einen Spaziergang!',
      indoor: 'Besser drinnen bleiben',
      rain: 'Vergessen Sie nicht den Regenschirm',
      cold: 'Ziehen Sie sich warm an',
    },
  },
  share: {
    title: 'Wetter teilen',
    current: 'Aktuelles Wetter',
    forecast: 'Wochenvorhersage',
    note: 'Teilen Sie das Wetter mit Freunden und Familie',
    success: 'Wetter erfolgreich geteilt',
    error: 'Fehler beim Teilen des Wetters',
  },
  activities: {
    title: 'Empfohlene Aktivitäten',
    subtitle: 'Basierend auf dem aktuellen Wetter',
    notRecommended: 'Nicht empfohlen',
  },
  history: {
    title: 'Wetterverlauf',
    temperature: 'Temperaturverlauf',
    humidity: 'Luftfeuchtigkeitsverlauf',
    wind: 'Windverlauf',
    noData: 'Keine Verlaufsdaten verfügbar',
  },
  errors: {
    locationError: 'Standorterkennungsfehler',
    networkError: 'Netzwerkfehler',
    apiError: 'Fehler beim Abrufen von Daten',
    locationPermission: 'Für Wetterinformationen wird Zugriff auf den Standort benötigt',
    locationUnavailable: 'Standort konnte nicht ermittelt werden. Bitte versuchen Sie es erneut',
    invalidApiKey: 'API-Schlüsselfehler. Überprüfen Sie die Konfiguration',
  },
  interactive: {
    title: 'Interaktiv',
    cloudSimulator: {
      title: 'Wolkenbildungssimulator',
      description: 'Erforschen Sie den Prozess der Bildung verschiedener Wolkentypen in einem interaktiven Modell. Erfahren Sie, wie Temperatur und Luftfeuchtigkeit die Bildung verschiedener Wolkenarten beeinflussen - von Zirruswolken bis zu Kumuluswolken.',
      instructions: [
        'Wählen Sie die Anfangslufttemperatur im Bereich von -10°C bis +50°C',
        'Stellen Sie die Luftfeuchtigkeit von 0% bis 100% ein',
        'Beobachten Sie den Kondensationsprozess und die Wolkenbildung',
        'Experimentieren Sie mit verschiedenen Bedingungen, um verschiedene Wolkentypen zu erzeugen',
      ],
      requirements: [
        'Moderner Browser mit WebGL-Unterstützung',
        'Stabile Internetverbindung',
      ],
      ageGroup: 'Teenager',
    },
  },
  quiz: {
    meteorologyBasics: {
      title: 'Grundlagen der Meteorologie',
      description: 'Testen Sie Ihr Wissen über grundlegende Konzepte in der Meteorologie',
      difficulty: 'leicht',
      duration: '10 Min',
      questionsCount: 5,
      startButton: 'Quiz starten',
    },
    weatherPhenomena: {
      title: 'Wetterphänomene',
      description: 'Test zum Wissen über verschiedene Wetterphänomene',
      difficulty: 'mittel',
      duration: '8 Min',
      questionsCount: 5,
      startButton: 'Quiz starten',
    },
  },
  today: 'Heute',
  partlyCloudy: 'Teilweise bewölkt',
  patchyRainNearby: 'Vereinzelte Regenfälle in der Nähe',
  rainFormation: 'Wie entsteht Regen?',
  thunderSound: 'Warum donnert es?',
  snowflakeShape: 'Warum sind Schneeflocken sechseckig?',
  rainbowFormation: 'Wie entsteht ein Regenbogen?',
  windCreation: 'Wie entsteht Wind?',
  humidityFacts: 'Was ist Luftfeuchtigkeit?',
  tornadoFormation: 'Wie entstehen Tornados?',
  auroraBorealis: 'Was ist das Polarlicht?',
  cloudTypes: 'Arten von Wolken',
  pressureEffects: 'Druckeffekte',
  lightningFacts: 'Fakten über Blitze',
  hurricaneEye: 'Auge des Hurrikans',
  fogFormation: 'Wie entsteht Nebel?',
  rainSmell: 'Was ist der Geruch nach dem Regen?',
  extremeWeather: 'Extreme Wetterrekorde?',
  weatherSatellites: 'Meteorologische Satelliten?',
  climateZones: 'Klimazonen?',
  weatherPrediction: 'Geschichte der Wettervorhersagen?',
}; 