export const en = {
  common: {
    loading: 'Loading...',
    error: 'Error',
    retry: 'Retry',
    settings: 'Settings',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    search: 'Search',
    ok: 'OK',
    weather: 'Weather',
  },
  settings: {
    title: 'Settings',
    appearance: 'Appearance',
    theme: 'Theme',
    language: 'Language',
    dark: 'Dark',
    light: 'Light',
    system: 'System',
    english: 'English',
    russian: 'Russian',
    spanish: 'Spanish',
    german: 'German',
    about: 'About',
    version: 'Version',
    units: 'Units',
    metric: 'Metric',
    imperial: 'Imperial',
  },
  weather: {
    temperature: 'Temperature',
    humidity: 'Humidity',
    wind: 'Wind',
    pressure: 'Pressure',
    feelsLike: 'Feels like',
    sunrise: 'Sunrise',
    sunset: 'Sunset',
    clear: 'Clear',
    cloudy: 'Cloudy',
    rain: 'Rain',
    snow: 'Snow',
    visibility: 'Visibility',
    precipitation: 'Precipitation',
    forecast: 'Forecast',
    uvIndex: 'UV Index',
    uvLow: 'Low',
    uvModerate: 'Moderate',
    uvHigh: 'High',
    uvVeryHigh: 'Very High',
    uvExtreme: 'Extreme',
    hourlyForecast: 'Hourly Forecast',
    dailyForecast: '7-day Forecast',
    temperatureChart: 'Temperature Chart',
    overcast: 'Overcast',
  },
  locations: {
    currentLocation: 'Current Location',
    searchPlaceholder: 'Search for a city...',
    favorites: 'Favorite Locations',
    addToFavorites: 'Add to Favorites',
    removeFromFavorites: 'Remove from Favorites',
    detectLocation: 'Detect Location',
    current: 'Current Location',
  },
  location: {
    success: 'Location found',
    cached: 'Using cached location',
    permissionDenied: 'Location permission denied',
    disabled: 'Location services disabled',
    noInternet: 'No internet connection',
    timeout: 'Location request timed out',
    error: 'Error getting location',
    unknown: 'Location status unknown',
    retry: 'Try again',
    settings: 'Open Settings',
  },
  astronomical: {
    title: 'Astronomical Data',
    sunrise: 'Sunrise',
    sunset: 'Sunset',
    moonrise: 'Moonrise',
    moonset: 'Moonset',
    illumination: 'Moon Illumination',
    newmoon: 'New Moon',
    waxingcrescent: 'Waxing Crescent',
    firstquarter: 'First Quarter',
    waxinggibbous: 'Waxing Gibbous',
    fullmoon: 'Full Moon',
    waninggibbous: 'Waning Gibbous',
    lastquarter: 'Last Quarter',
    waningcrescent: 'Waning Crescent',
  },
  airQuality: {
    title: 'Air Quality',
    good: 'Good',
    moderate: 'Moderate',
    unhealthyForSensitive: 'Unhealthy for Sensitive Groups',
    unhealthy: 'Unhealthy',
    veryUnhealthy: 'Very Unhealthy',
    hazardous: 'Hazardous',
    unknown: 'Unknown',
    index: 'EPA Index',
  },
  units: {
    temperature: '°C',
    speed: 'km/h',
    pressure: 'mb',
    precipitation: 'mm',
    distance: 'km',
  },
  unitsImperial: {
    temperature: '°F',
    speed: 'mph',
    pressure: 'inHg',
    precipitation: 'in',
    distance: 'mi',
  },
  directions: {
    N: 'N',
    NNE: 'NNE',
    NE: 'NE',
    ENE: 'ENE',
    E: 'E',
    ESE: 'ESE',
    SE: 'SE',
    SSE: 'SSE',
    S: 'S',
    SSW: 'SSW',
    SW: 'SW',
    WSW: 'WSW',
    W: 'W',
    WNW: 'WNW',
    NW: 'NW',
    NNW: 'NNW',
  },
  recommendations: {
    title: 'Recommendations',
    clothing: {
      warm: 'Wear warm clothes',
      light: 'Light clothing will do',
      raincoat: 'Take an umbrella or raincoat',
      winter: 'Wear warm winter clothes',
    },
    activities: {
      perfect: 'Perfect weather for a walk!',
      indoor: 'Better stay indoors',
      rain: "Don't forget an umbrella",
      cold: 'Dress warmly',
    },
  },
  share: {
    title: 'Share Weather',
    current: 'Current Weather',
    forecast: 'Weekly Forecast',
    note: 'Share weather with friends and family',
    success: 'Weather shared successfully',
    error: 'Error sharing weather',
  },
  activities: {
    title: 'Recommended Activities',
    subtitle: 'Based on current weather',
    notRecommended: 'Not Recommended',
  },
  history: {
    title: 'Weather History',
    temperature: 'Temperature History',
    humidity: 'Humidity History',
    wind: 'Wind History',
    noData: 'No history data available',
  },
  errors: {
    locationError: 'Location detection error',
    networkError: 'Network error',
    apiError: 'Data fetching error',
    locationPermission: 'Location access is required for weather data',
    locationUnavailable: 'Could not get location. Please try again',
    invalidApiKey: 'API key error. Check configuration',
  },
  today: 'Today',
  partlyCloudy: 'Partly Cloudy',
  patchyRainNearby: 'Patchy rain nearby',
  rainFormation: 'How is rain formed?',
  thunderSound: 'Why does thunder rumble?',
  snowflakeShape: 'Why are snowflakes hexagonal?',
  rainbowFormation: 'How is a rainbow formed?',
  windCreation: 'How does wind arise?',
  humidityFacts: 'What is humidity?',
  tornadoFormation: 'How are tornadoes formed?',
  auroraBorealis: 'What is the aurora borealis?',
  fogFormation: 'How is fog formed?',
  rainSmell: 'What is the smell after rain?',
  extremeWeather: 'Extreme weather records?',
  weatherSatellites: 'Meteorological satellites?',
  climateZones: 'Climate zones?',
  weatherPrediction: 'History of weather forecasts?',
  cloudTypes: 'Types of clouds',
  pressureEffects: 'Effects of pressure',
  lightningFacts: 'Facts about lightning',
  hurricaneEye: 'Eye of the hurricane',
}; 