export const en = {
  common: {
    loading: 'Loading...',
    error: 'Error',
    retry: 'Retry',
    settings: 'Settings',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    search: 'Search',
  },
  settings: {
    title: 'Settings',
    appearance: 'Appearance',
    theme: 'Theme',
    language: 'Language',
    dark: 'Dark',
    light: 'Light',
    about: 'About',
    version: 'Version',
  },
  weather: {
    temperature: 'Temperature',
    humidity: 'Humidity',
    wind: 'Wind',
    pressure: 'Pressure',
    feelsLike: 'Feels like',
    sunrise: 'Sunrise',
    sunset: 'Sunset',
    clear: 'Clear',
    cloudy: 'Cloudy',
    rain: 'Rain',
    snow: 'Snow',
    visibility: 'Visibility',
    precipitation: 'Precipitation',
    forecast: 'Forecast',
    uvIndex: 'UV Index',
    uvLow: 'Low',
    uvModerate: 'Moderate',
    uvHigh: 'High',
    uvVeryHigh: 'Very High',
    uvExtreme: 'Extreme',
    hourlyForecast: 'Hourly Forecast',
  },
  locations: {
    currentLocation: 'Current Location',
    searchPlaceholder: 'Search city...',
    favorites: 'Favorite Cities',
    addToFavorites: 'Add to Favorites',
    removeFromFavorites: 'Remove from Favorites',
    detectLocation: 'Detect Location',
    current: 'Current Location',
  },
  astronomical: {
    title: 'Astronomical Data',
    sunrise: 'Sunrise',
    sunset: 'Sunset',
    moonrise: 'Moonrise',
    moonset: 'Moonset',
    illumination: 'Moon Illumination',
    newmoon: 'New Moon',
    waxingcrescent: 'Waxing Crescent',
    firstquarter: 'First Quarter',
    waxinggibbous: 'Waxing Gibbous',
    fullmoon: 'Full Moon',
    waninggibbous: 'Waning Gibbous',
    lastquarter: 'Last Quarter',
    waningcrescent: 'Waning Crescent',
  },
  airQuality: {
    title: 'Air Quality',
    good: 'Good',
    moderate: 'Moderate',
    unhealthyForSensitive: 'Unhealthy for Sensitive Groups',
    unhealthy: 'Unhealthy',
    veryUnhealthy: 'Very Unhealthy',
    hazardous: 'Hazardous',
  },
  directions: {
    N: 'N',
    NNE: 'NNE',
    NE: 'NE',
    ENE: 'ENE',
    E: 'E',
    ESE: 'ESE',
    SE: 'SE',
    SSE: 'SSE',
    S: 'S',
    SSW: 'SSW',
    SW: 'SW',
    WSW: 'WSW',
    W: 'W',
    WNW: 'WNW',
    NW: 'NW',
    NNW: 'NNW',
  },
  recommendations: {
    title: 'Recommendations',
    clothing: {
      warm: 'Wear warm clothes',
      light: 'Light clothing will do',
      raincoat: 'Take an umbrella or raincoat',
      winter: 'Wear warm winter clothes',
    },
    activities: {
      perfect: 'Perfect weather for a walk!',
      indoor: 'Better stay indoors',
      rain: "Don't forget an umbrella",
      cold: 'Dress warmly',
    },
  },
  errors: {
    locationError: 'Location detection error',
    networkError: 'Network error',
    apiError: 'Data fetching error',
  },
}; 