export const es = {
  common: {
    loading: 'Cargando...',
    error: 'Error',
    retry: 'Reintentar',
    settings: 'Configuración',
    cancel: 'Cancelar',
    save: 'Guardar',
    delete: 'Eliminar',
    edit: 'Editar',
    search: 'Buscar',
    ok: 'OK',
  },
  settings: {
    title: 'Configuración',
    appearance: 'Apariencia',
    theme: 'Tema',
    language: 'Idioma',
    dark: 'Oscuro',
    light: 'Claro',
    system: 'Sistema',
    english: 'Inglés',
    russian: 'Ruso',
    spanish: 'Español',
    german: 'Alemán',
    about: 'Acerca de',
    version: 'Versión',
    units: 'Unidades',
    metric: 'Métrico',
    imperial: 'Imperial',
  },
  weather: {
    temperature: 'Temperatura',
    humidity: 'Humedad',
    wind: 'Viento',
    pressure: 'Presión',
    feelsLike: 'Sensación térmica',
    sunrise: 'Amanecer',
    sunset: 'Atardecer',
    clear: 'Despejado',
    cloudy: 'Nublado',
    rain: 'Lluvia',
    snow: 'Nieve',
    visibility: 'Visibilidad',
    precipitation: 'Precipitación',
    forecast: 'Pronóstico',
    uvIndex: 'Índice UV',
    uvLow: 'Bajo',
    uvModerate: 'Moderado',
    uvHigh: 'Alto',
    uvVeryHigh: 'Muy alto',
    uvExtreme: 'Extremo',
    hourlyForecast: 'Pronóstico por hora',
    dailyForecast: 'Pronóstico de 7 días',
    temperatureChart: 'Gráfico de temperatura',
    overcast: 'Cubierto',
  },
  locations: {
    currentLocation: 'Ubicación actual',
    searchPlaceholder: 'Buscar ciudad...',
    favorites: 'Ciudades favoritas',
    addToFavorites: 'Añadir a favoritos',
    removeFromFavorites: 'Eliminar de favoritos',
    detectLocation: 'Detectar ubicación',
    current: 'Ubicación actual',
  },
  astronomical: {
    title: 'Datos astronómicos',
    sunrise: 'Amanecer',
    sunset: 'Atardecer',
    moonrise: 'Salida de la luna',
    moonset: 'Puesta de la luna',
    illumination: 'Iluminación lunar',
    newmoon: 'Luna nueva',
    waxingcrescent: 'Luna creciente',
    firstquarter: 'Cuarto creciente',
    waxinggibbous: 'Luna gibosa creciente',
    fullmoon: 'Luna llena',
    waninggibbous: 'Luna gibosa menguante',
    lastquarter: 'Cuarto menguante',
    waningcrescent: 'Luna menguante',
  },
  airQuality: {
    title: 'Calidad del aire',
    good: 'Buena',
    moderate: 'Moderada',
    unhealthyForSensitive: 'Insalubre para grupos sensibles',
    unhealthy: 'Insalubre',
    veryUnhealthy: 'Muy insalubre',
    hazardous: 'Peligrosa',
    unknown: 'Desconocida',
    index: 'Índice EPA',
  },
  units: {
    temperature: '°C',
    speed: 'km/h',
    pressure: 'mb',
    precipitation: 'mm',
    distance: 'km',
  },
  unitsImperial: {
    temperature: '°F',
    speed: 'mph',
    pressure: 'inHg',
    precipitation: 'in',
    distance: 'mi',
  },
  directions: {
    N: 'N',
    NNE: 'NNE',
    NE: 'NE',
    ENE: 'ENE',
    E: 'E',
    ESE: 'ESE',
    SE: 'SE',
    SSE: 'SSE',
    S: 'S',
    SSW: 'SSO',
    SW: 'SO',
    WSW: 'OSO',
    W: 'O',
    WNW: 'ONO',
    NW: 'NO',
    NNW: 'NNO',
  },
  recommendations: {
    title: 'Recomendaciones',
    clothing: {
      warm: 'Use ropa abrigada',
      light: 'La ropa ligera será suficiente',
      raincoat: 'Lleve un paraguas o impermeable',
      winter: 'Use ropa de invierno abrigada',
    },
    activities: {
      perfect: '¡Clima perfecto para un paseo!',
      indoor: 'Mejor quedarse en casa',
      rain: 'No olvide el paraguas',
      cold: 'Abríguese bien',
    },
  },
  share: {
    title: 'Compartir clima',
    current: 'Clima actual',
    forecast: 'Pronóstico semanal',
    note: 'Comparta el clima con amigos y familiares',
    success: 'Clima compartido con éxito',
    error: 'Error al compartir el clima',
  },
  activities: {
    title: 'Actividades recomendadas',
    subtitle: 'Basado en el clima actual',
    notRecommended: 'No recomendado',
  },
  history: {
    title: 'Historial del clima',
    temperature: 'Historial de temperatura',
    humidity: 'Historial de humedad',
    wind: 'Historial de viento',
    noData: 'No hay datos históricos disponibles',
  },
  errors: {
    locationError: 'Error de detección de ubicación',
    networkError: 'Error de red',
    apiError: 'Error al obtener datos',
    locationPermission: 'Se necesita acceso a la ubicación para obtener el clima',
    locationUnavailable: 'No se pudo obtener la ubicación. Por favor, inténtelo de nuevo',
    invalidApiKey: 'Error de clave API. Verifique la configuración',
  },
  interactive: {
    title: 'Interactivo',
    cloudSimulator: {
      title: 'Simulador de formación de nubes',
      description: 'Explore el proceso de formación de diferentes tipos de nubes en un modelo interactivo. Aprenda cómo la temperatura y la humedad afectan la formación de nubes de diferentes tipos, desde cirros hasta cúmulos.',
      instructions: [
        'Seleccione la temperatura inicial del aire en el rango de -10°C a +50°C',
        'Establezca el nivel de humedad del aire de 0% a 100%',
        'Observe el proceso de condensación y formación de nubes',
        'Experimente con diferentes condiciones para crear varios tipos de nubes',
      ],
      requirements: [
        'Navegador moderno con soporte para WebGL',
        'Conexión a Internet estable',
      ],
      ageGroup: 'adolescente',
    },
  },
  quiz: {
    meteorologyBasics: {
      title: 'Fundamentos de meteorología',
      description: 'Compruebe sus conocimientos sobre conceptos básicos de meteorología',
      difficulty: 'fácil',
      duration: '10 min',
      questionsCount: 5,
      startButton: 'Iniciar cuestionario',
    },
    weatherPhenomena: {
      title: 'Fenómenos meteorológicos',
      description: 'Prueba sobre el conocimiento de varios fenómenos meteorológicos',
      difficulty: 'medio',
      duration: '8 min',
      questionsCount: 5,
      startButton: 'Iniciar cuestionario',
    },
  },
  today: 'Hoy',
  partlyCloudy: 'Parcialmente nublado',
  patchyRainNearby: 'Lluvia dispersa cerca',
  rainFormation: '¿Cómo se forma la lluvia?',
  thunderSound: '¿Por qué retumba el trueno?',
  snowflakeShape: '¿Por qué son hexagonales los copos de nieve?',
  rainbowFormation: '¿Cómo se forma un arcoíris?',
  windCreation: '¿Cómo se origina el viento?',
  humidityFacts: '¿Qué es la humedad?',
  tornadoFormation: '¿Cómo se forman los tornados?',
  auroraBorealis: '¿Qué es la aurora boreal?',
  cloudTypes: 'Tipos de nubes',
  pressureEffects: 'Efectos de presión',
  lightningFacts: 'Datos sobre los relámpagos',
  hurricaneEye: 'Ojo del huracán',
  fogFormation: '¿Cómo se forma la niebla?',
  rainSmell: '¿Cuál es el olor después de la lluvia?',
  extremeWeather: '¿Récords de clima extremo?',
  weatherSatellites: '¿Satélites meteorológicos?',
  climateZones: '¿Zonas climáticas?',
  weatherPrediction: '¿Historia de las predicciones meteorológicas?',
}; 