export const ru = {
  common: {
    loading: 'Загрузка...',
    error: 'Ошибка',
    retry: 'Повторить',
    cancel: 'Отмена',
    save: 'Сохранить',
    delete: 'Удалить',
    edit: 'Изменить',
    search: 'Поиск',
    settings: 'Настройки',
    ok: 'OK',
  },
  weather: {
    temperature: 'Температура',
    feelsLike: 'Ощущается как',
    humidity: 'Влажность',
    wind: 'Ветер',
    pressure: 'Давление',
    visibility: 'Видимость',
    precipitation: 'Осадки',
    forecast: 'Прогноз',
    recommendations: {
      title: 'Рекомендации',
      clothing: 'Одежда',
      umbrella: 'Зонт',
      activity: 'Активность',
    },
    uvIndex: 'УФ-индекс',
    uvLow: 'Низкий',
    uvModerate: 'Умеренный',
    uvHigh: 'Высокий',
    uvVeryHigh: 'Очень высокий',
    uvExtreme: 'Экстремальный',
    hourlyForecast: 'Почасовой прогноз',
    dailyForecast: '7-дневный прогноз',
    temperatureChart: 'График температуры',
    clear: 'Ясно',
    cloudy: 'Облачно',
    rain: 'Дождь',
    snow: 'Снег',
    sunrise: 'Восход',
    sunset: 'Закат',
  },
  search: {
    placeholder: 'Поиск города...',
    useLocation: 'Использовать текущее местоположение',
  },
  errors: {
    locationPermission: 'Для получения погоды необходим доступ к местоположению',
    locationUnavailable: 'Не удалось получить местоположение. Пожалуйста, попробуйте снова',
    networkError: 'Ошибка сети',
    apiError: 'Ошибка получения данных',
    invalidApiKey: 'Ошибка API ключа. Проверьте конфигурацию',
    locationError: 'Ошибка определения местоположения',
  },
  airQuality: {
    title: 'Качество воздуха',
    good: 'Хорошее',
    moderate: 'Умеренное',
    unhealthyForSensitive: 'Вредно для чувствительных групп',
    unhealthy: 'Вредно',
    veryUnhealthy: 'Очень вредно',
    hazardous: 'Опасно',
    unknown: 'Неизвестно',
    index: 'Индекс EPA',
  },
  astronomical: {
    title: 'Астрономические данные',
    sunrise: 'Восход солнца',
    sunset: 'Закат солнца',
    moonrise: 'Восход луны',
    moonset: 'Закат луны',
    illumination: 'Освещенность луны',
    newmoon: 'Новолуние',
    waxingcrescent: 'Растущий серп',
    firstquarter: 'Первая четверть',
    waxinggibbous: 'Растущая луна',
    fullmoon: 'Полнолуние',
    waninggibbous: 'Убывающая луна',
    lastquarter: 'Последняя четверть',
    waningcrescent: 'Убывающий серп',
  },
  units: {
    temperature: '°C',
    speed: 'км/ч',
    pressure: 'мб',
    precipitation: 'мм',
    distance: 'км',
  },
  directions: {
    N: 'С',
    NNE: 'ССВ',
    NE: 'СВ',
    ENE: 'ВСВ',
    E: 'В',
    ESE: 'ВЮВ',
    SE: 'ЮВ',
    SSE: 'ЮЮВ',
    S: 'Ю',
    SSW: 'ЮЮЗ',
    SW: 'ЮЗ',
    WSW: 'ЗЮЗ',
    W: 'З',
    WNW: 'ЗСЗ',
    NW: 'СЗ',
    NNW: 'ССЗ',
  },
  interactive: {
    title: 'Интерактив',
    cloudSimulator: {
      title: 'Симулятор формирования облаков',
      description: 'Исследуйте процесс образования различных типов облаков в интерактивной модели. Узнайте, как температура и влажность влияют на формирование облаков разных видов - от перистых до кучевых.',
      instructions: [
        'Выберите начальную температуру воздуха в диапазоне от -10°C до +50°C',
        'Установите уровень влажности воздуха от 0% до 100%',
        'Наблюдайте за процессом конденсации и формированием облаков',
        'Экспериментируйте с разными условиями для создания различных типов облаков',
      ],
      requirements: [
        'Современный браузер с поддержкой WebGL',
        'Стабильное интернет-соединение',
      ],
      ageGroup: 'teenager',
    },
    tornadoExperiment: {
      title: 'Эксперимент: Создание торнадо в бутылке',
      description: 'Создайте безопасную модель торнадо в домашних условиях. Этот эксперимент поможет понять принципы формирования вихревых потоков в атмосфере и механизм образования торнадо.',
      instructions: [
        'Наполните пластиковую бутылку водой, оставив немного воздуха',
        'Добавьте несколько капель пищевого красителя или блестки для лучшей визуализации',
        'Переверните бутылку вверх дном и создайте вращательное движение',
        'Наблюдайте за формированием воронки и обратите внимание на скорость вращения',
      ],
      requirements: [
        'Прозрачная пластиковая бутылка с крышкой',
        'Чистая вода комнатной температуры',
        'Пищевой краситель или блестки',
        'Помощь взрослых при проведении эксперимента',
      ],
      ageGroup: 'children',
    },
  },
  quiz: {
    meteorologyBasics: {
      title: 'Основы метеорологии',
      description: 'Проверьте свои знания о базовых понятиях в метеорологии',
      difficulty: 'easy',
      duration: '10 мин',
      questionsCount: 5,
      startButton: 'Начать викторину',
    },
    weatherPhenomena: {
      title: 'Погодные явления',
      description: 'Тест на знание различных погодных явлений',
      difficulty: 'medium',
      duration: '8 мин',
      questionsCount: 5,
      startButton: 'Начать викторину',
    },
    climateAndWeather: {
      title: 'Климат и погода',
      description: 'Проверьте свои знания о климатических особенностях',
      difficulty: 'medium',
      duration: '9 мин',
      questionsCount: 3,
      startButton: 'Начать викторину',
    },
    atmosphericPhenomena: {
      title: 'Атмосферные явления',
      description: 'Углубленный тест по атмосферным явлениям',
      difficulty: 'hard',
      duration: '12 мин',
      questionsCount: 3,
      startButton: 'Начать викторину',
    },
  },
  locations: {
    current: 'Текущее местоположение',
    favorites: 'Избранные города',
    addToFavorites: 'Добавить в избранное',
    removeFromFavorites: 'Удалить из избранного',
    detectLocation: 'Определить местоположение',
    searchPlaceholder: 'Поиск города...',
    currentLocation: 'Текущее местоположение',
  },
  settings: {
    title: 'Настройки',
    appearance: 'Внешний вид',
    theme: 'Тема',
    language: 'Язык',
    notifications: 'Уведомления',
    location: 'Местоположение',
    dark: 'Тёмная',
    light: 'Светлая',
    system: 'Системная',
    english: 'Английский',
    russian: 'Русский',
    about: 'О приложении',
    version: 'Версия',
  },
  recommendations: {
    title: 'Рекомендации',
    clothing: {
      warm: 'Наденьте теплую одежду',
      light: 'Подойдет легкая одежда',
      raincoat: 'Возьмите зонт или дождевик',
      winter: 'Наденьте теплую зимнюю одежду',
    },
    activities: {
      perfect: 'Отличная погода для прогулки!',
      indoor: 'Лучше остаться дома',
      rain: 'Не забудьте зонт',
      cold: 'Оденьтесь теплее',
    },
  },
  share: {
    title: 'Поделиться погодой',
    current: 'Текущая погода',
    forecast: 'Прогноз на неделю',
    note: 'Поделитесь погодой с друзьями и близкими',
    success: 'Погода успешно отправлена',
    error: 'Ошибка при отправке погоды',
  },
  activities: {
    title: 'Рекомендуемые активности',
    subtitle: 'На основе текущей погоды',
    notRecommended: 'Не рекомендуется',
  },
  history: {
    title: 'История погоды',
    temperature: 'История температуры',
    humidity: 'История влажности',
    wind: 'История ветра',
    noData: 'Нет данных истории',
  },
}; 